const test=require('node:test');
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const {normalizeCheckoutRequest,verifyStripeSignature,handleRequest}=require('../backend/stripe-worker.cjs');
const catalog={currency:'EUR',products:[{handle:'sample-wig',title:'Sample Wig',variants:[{title:'18 / HD',opt1:'18',opt2:'HD',opt3:null,opt4:null,price_eur:199.99}]}]};
const request=(country='Portugal')=>({customer:{name:'Test Buyer',email:'buyer@example.com',phone:'+351****5678',country,address:'Rua A',city:'Lisbon',postalCode:'1000-001'},items:[{handle:'sample-wig',options:{opt1:'18',opt2:'HD'},quantity:2}]});
test('shipping quote endpoint returns the server-owned regional rate',async()=>{const env={SITE_ORIGIN:'https://jashe1728.github.io'};const response=await handleRequest(new Request('https://worker.example/shipping-quote',{method:'POST',headers:{Origin:env.SITE_ORIGIN,'Content-Type':'text/plain'},body:JSON.stringify({country:'United States'})}),env);assert.equal(response.status,200);assert.deepEqual(await response.json(),{currency:'EUR',region:'US',shippingCents:1500});});
test('shipping quote endpoint rejects destinations without configured rates',async()=>{const env={SITE_ORIGIN:'https://jashe1728.github.io'};const response=await handleRequest(new Request('https://worker.example/shipping-quote',{method:'POST',headers:{Origin:env.SITE_ORIGIN,'Content-Type':'text/plain'},body:JSON.stringify({country:'Canada'})}),env);assert.equal(response.status,422);});

test('checkout resolves free EU shipping from destination',()=>{const x=normalizeCheckoutRequest(request('Portugal'),catalog,{});assert.equal(x.shippingCents,0);assert.equal(x.totalCents,39998);assert.equal(x.lineItems.length,1);assert.equal(normalizeCheckoutRequest(request('Deutschland'),catalog,{}).shippingCents,0);});
test('checkout charges EUR 20 for supported African destinations and limits Stripe shipping choices to that rate group',()=>{const x=normalizeCheckoutRequest(request('Mozambique'),catalog,{});assert.equal(x.shippingCents,2000);assert.equal(x.totalCents,41998);assert.deepEqual(x.allowedCountries.slice().sort(),['AO','CI','CV','GW','MZ','SN','ST','ZA']);});
test('checkout charges EUR 15 for the United States',()=>{const x=normalizeCheckoutRequest(request('United States'),catalog,{});assert.equal(x.shippingCents,1500);assert.equal(x.totalCents,41498);});
test('checkout rejects a destination without an approved shipping rate',()=>{assert.throws(()=>normalizeCheckoutRequest(request('Canada'),catalog,{}),/shipping.*destination/i);});
test('checkout computes EUR cents and resolves variant price from canonical catalog',()=>{const x=normalizeCheckoutRequest(request('Portugal'),catalog,{});assert.equal(x.subtotalCents,39998);assert.equal(x.totalCents,39998);assert.equal(x.lineItems[0].price_data.unit_amount,19999);});
test('checkout rejects forged prices and unknown variants',()=>{const forged=request();forged.items[0].price=1;assert.throws(()=>normalizeCheckoutRequest(forged,catalog,{}),/unexpected|invalid/i);const unknown=request();unknown.items[0].options.opt1='99';assert.throws(()=>normalizeCheckoutRequest(unknown,catalog,{}),/variant|option/i);});
test('checkout rejects invalid customer data and quantity',()=>{const bad=request();bad.customer.email='bad';assert.throws(()=>normalizeCheckoutRequest(bad,catalog,{}),/email/i);const qty=request();qty.items[0].quantity=0;assert.throws(()=>normalizeCheckoutRequest(qty,catalog,{}),/quantity/i);});
test('Stripe signature rejects tampered and stale webhook bodies',()=>{const secret='whsec_test',timestamp=Math.floor(Date.now()/1000),body='{"id":"evt_1"}',digest=crypto.createHmac('sha256',secret).update(`${timestamp}.${body}`).digest('hex');assert.equal(verifyStripeSignature(body,`t=${timestamp},v1=${digest}`,secret),true);assert.equal(verifyStripeSignature(body+' ',`t=${timestamp},v1=${digest}`,secret),false);assert.equal(verifyStripeSignature(body,`t=${timestamp-600},v1=${digest}`,secret),false);});
test('checkout handler creates Stripe Session with server-priced line items and correct Pages return URL',async()=>{const oldFetch=global.fetch;let stripeBody='';let stripeAuthOk=false;const gasForwards=[];global.fetch=async(url,options)=>{if(url==='https://catalog.example/catalog.json')return Response.json(catalog);if(url==='https://gas.example/exec'){gasForwards.push(JSON.parse(options.body));return Response.json({ok:true});}stripeAuthOk=options.headers.authorization==='Bearer sk_test_fake';stripeBody=options.body;return Response.json({url:'https://checkout.stripe.com/c/pay/cs_test'});};const env={SITE_ORIGIN:'https://jashe1728.github.io',SITE_BASE_URL:'https://jashe1728.github.io/asheerah-hair',CATALOG_URL:'https://catalog.example/catalog.json',STRIPE_SECRET_KEY:'sk_test_fake',STRIPE_WEBHOOK_SECRET:'whsec_test',WORKER_GAS_SECRET:'gas_test',GAS_WEBHOOK_URL:'https://gas.example/exec'};try{const response=await handleRequest(new Request('https://worker.example/create-checkout-session',{method:'POST',headers:{Origin:env.SITE_ORIGIN,'Content-Type':'text/plain'},body:JSON.stringify(request('Mozambique'))}),env);const result=await response.json();const params=new URLSearchParams(stripeBody);const pending=JSON.parse(gasForwards[0].payload);assert.equal(response.status,200);assert.equal(stripeAuthOk,true);assert.equal(pending.action,'stripe_pending');assert.equal(pending.expectedTotalCents,41998);assert.equal(gasForwards[0].signature.length,64);assert.equal(JSON.parse(gasForwards[1].payload).action,'stripe_session_created');assert.equal(result.checkoutUrl,'https://checkout.stripe.com/c/pay/cs_test');assert.equal(params.get('line_items[0][price_data][unit_amount]'),'19999');assert.equal(params.get('line_items[1][price_data][unit_amount]'),'2000');assert.equal(params.get('success_url').startsWith(`${env.SITE_BASE_URL}/checkout.html?payment=success`),true);assert.equal(params.get('metadata[expected_total_cents]'),'41998');assert.deepEqual(params.getAll('shipping_address_collection[allowed_countries][]').slice().sort(),['AO','CI','CV','GW','MZ','SN','ST','ZA']);}finally{global.fetch=oldFetch;}});
test('Stripe webhook verifies the raw signature without Origin and forwards an HMAC wrapper',async()=>{const secret='whsec_test',gasSecret='worker-gas';const event={id:'evt_session',type:'checkout.session.completed',data:{object:{id:'cs_test',client_reference_id:'ord_test',amount_total:42998,currency:'eur',payment_status:'paid',metadata:{expected_total_cents:'42998'}}}};const body=JSON.stringify(event),timestamp=Math.floor(Date.now()/1000),signature=crypto.createHmac('sha256',secret).update(`${timestamp}.${body}`).digest('hex');const oldFetch=global.fetch;let forwarded;global.fetch=async(_url,opts)=>{forwarded=JSON.parse(opts.body);return Response.json({ok:true});};try{const res=await handleRequest(new Request('https://worker.example/webhook',{method:'POST',headers:{'Stripe-Signature':`t=${timestamp},v1=${signature}`},body}),{STRIPE_WEBHOOK_SECRET:secret,GAS_WEBHOOK_URL:'https://gas.example/exec',WORKER_GAS_SECRET:gasSecret});assert.equal(res.status,200);assert.equal(typeof forwarded.payload,'string');assert.match(forwarded.signature,/^[a-f0-9]{64}$/);assert.equal(Object.hasOwn(JSON.parse(forwarded.payload),'sharedSecret'),false);}finally{global.fetch=oldFetch;}});
