const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const crypto=require('node:crypto');
const source=fs.readFileSync(require.resolve('../backend/Code.gs'),'utf8');
function harness(){const rows=[['Event ID','Order ID','Status','Stripe Session ID','Payment Intent ID','Customer Email','Customer Phone','Ship To','Shipping Address','Items','Amount €','Currency','Updated At']];const sheet={getDataRange:()=>({getValues:()=>rows.map(r=>r.slice())}),appendRow:r=>rows.push(r.slice()),getRange:(row,col)=>({setValue:v=>{rows[row-1][col-1]=v;}})};const context={LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){}})},MailApp:{sendEmail(){}},PropertiesService:{getScriptProperties:()=>({getProperty:k=>k==='WORKER_GAS_SECRET'?'worker-gas':null})},Utilities:{computeHmacSha256Signature:(body,key)=>Array.from(crypto.createHmac('sha256',key).update(body).digest())},getSheet_:()=>sheet,safeCell_:(v,max)=>String(v||'').slice(0,max),r2:v=>Math.round(v*100)/100};vm.createContext(context);vm.runInContext(source,context);context.getSheet_=()=>sheet;return{context,rows};}
const pending={action:'stripe_pending',orderId:'123e4567-e89b-42d3-a456-426614174000',customer:{name:'A Buyer',email:'buyer@example.com',phone:'+351912345678',country:'PT',address:'Street 1',city:'Lisbon',postalCode:'1000'},itemsSummary:'2x Sample Wig',expectedTotalCents:42998,subtotalCents:39998,shippingCents:3000,currency:'EUR'};
test('Apps Script authenticates the exact Worker payload with HMAC',()=>{const h=harness();const payload=JSON.stringify({action:'stripe_pending'});const signature=crypto.createHmac('sha256','worker-gas').update(payload).digest('hex');assert.deepEqual(JSON.parse(JSON.stringify(h.context.verifyWorkerPayload_({payload,signature}))),{action:'stripe_pending'});assert.equal(h.context.verifyWorkerPayload_({payload,signature:'0'.repeat(64)}),null);});
test('trusted pending order is recorded before Stripe checkout is returned',()=>{const h=harness();const result=h.context.processStripeWorkerPayload_(pending);assert.equal(result.ok,true);assert.equal(h.rows.length,2);assert.equal(h.rows[1][2],'pending');assert.equal(h.rows[1][10],429.98);assert.match(h.rows[1][8],/Street 1/);});
test('Stripe session ID is attached to the matching pending order',()=>{const h=harness();h.context.processStripeWorkerPayload_(pending);const r=h.context.processStripeWorkerPayload_({action:'stripe_session_created',orderId:pending.orderId,sessionId:'cs_test_123'});assert.equal(r.ok,true);assert.equal(h.rows[1][3],'cs_test_123');});
test('only a matching signed paid session can update the order to paid',()=>{const h=harness();h.context.processStripeWorkerPayload_(pending);h.context.processStripeWorkerPayload_({action:'stripe_session_created',orderId:pending.orderId,sessionId:'cs_test_123'});const event={action:'stripe_event',eventId:'evt_123',eventType:'checkout.session.completed',session:{id:'cs_test_123',client_reference_id:pending.orderId,amount_total:42998,currency:'eur',payment_status:'paid',payment_intent:'pi_test',metadata:{order_id:pending.orderId,expected_total_cents:'42998',items_summary:'2x Sample Wig'},customer_details:{email:'buyer@example.com',phone:'+351912345678'},shipping_details:{name:'A Buyer',address:{line1:'Street 1',city:'Lisbon',postal_code:'1000',country:'PT'}}}};const result=h.context.processStripeWorkerPayload_(event);assert.equal(result.status,'paid');assert.equal(h.rows.length,2);assert.equal(h.rows[1][2],'paid');assert.equal(h.rows[1][4],'pi_test');});
test('mismatched Stripe amount is rejected and order remains pending',()=>{const h=harness();h.context.processStripeWorkerPayload_(pending);h.context.processStripeWorkerPayload_({action:'stripe_session_created',orderId:pending.orderId,sessionId:'cs_test_123'});const result=h.context.processStripeWorkerPayload_({action:'stripe_event',eventId:'evt_bad',eventType:'checkout.session.completed',session:{id:'cs_test_123',client_reference_id:pending.orderId,amount_total:1,currency:'eur',payment_status:'paid',metadata:{order_id:pending.orderId,expected_total_cents:'42998'}}});assert.equal(result.ok,false);assert.equal(h.rows[1][2],'pending');});
